//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LasProg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Products Products { get; set; }
    }
}
